apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "creators.name" . }}
  labels:
    {{- include "creators.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "creators.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "creators.labels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "creators.pod" . | nindent 6 }}
      containers:
        - name: application
          {{- include "creators.container" . | nindent 10 }}
          ports:
            - name: http
              containerPort: 8000
          startupProbe:
            httpGet: {path: /health, port: http}
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet: {path: /health, port: http}
            periodSeconds: 15
          readinessProbe:
            httpGet: {path: /ready, port: http}
            periodSeconds: 10
            timeoutSeconds: 5
