apiVersion: v1
kind: Service
metadata:
  name: {{ include "creators.name" . }}
spec:
  selector:
    {{- include "creators.labels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
